config/routes.rb
Rails.application.routes.draw do
  get 'article/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
get 'welcome/home', to: 'welcome#home'
get 'welcome/about', to: 'welcome#about'

resources :articles do
	  resources :comments
end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	has_many :comments, dependent: :destroy
	validates :title, presence:true, length: { minimum: 3, maximum: 50 }
	validates :description, presence: true, length: {minimum: 5, maximum: 300} 

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	#thse should all set_atcile before they fun
	before_action :set_article , only: [:edit, :update, :show, :destroy]
	http_basic_authenticate_with name: "fred", password: "fred123", except: [:index, :show]

	def index
	@articles = Article.all
	end

	def new
		@article = Article.new
	end
	def create
		#render plain: params[:article].inspect #display in browser what is being savaed
		@article = Article.new(article_params)
		if @article.save
			flash[:notice] = "Article was Created successfully"
			redirect_to articles_path(@article)
		else
			render 'new'
		end
	end
	def edit

	end
def update
	if @article.update(article_params)
		flash[:notice] = "Article was udpated successfully"
		redirect_to article_path(@article)
	else
		render 'edit'
	end

end


def show


end
def destroy
	@article.destroy
	flash[:notice] = "Article was deleted sucessfully"
	redirect_to articles_path


end


	private
	def set_article
		@article = Article.find(params[:id])
	end

	def article_params
		params.require(:article).permit(:title, :description)
	end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
http_basic_authenticate_with name: "fred", password: "fred123", only: :destroy

	
	def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

 def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end

 
  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

def home

end

def about
end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/article_helper.rb
module ArticleHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/activity/mine.html.erb
<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1 class="m-0 text-dark">Some Page</h1>
      </div>
    </div>
  </div>
</div>
<section class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12">
        <div class="card">
          <div class="card-body">
            <span>Stuff</span>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/articles/_form.html.erb
<% if @article.errors.any? %>

        <h2>The following errors prevented the article from getting created</h2>

        <ul>

                <% @article.errors.full_messages.each do |msg| %>

                        <li><%= msg %></li>

                <% end %>

        </ul>

<% end %>
<div class="container text-center">
<%= form_for @article do |f| %>
	<div class="form-group">
	<p>
	<%= f.label :title %> <br />
        <%= f.text_field :title, class: "form-control" %>
	</p>
	</div>
	  <div class="form-group">
	<p>
        <%= f.label :description %> <br />
        <%= f.text_area  :description, class: "form-control" %>
        </p>
        <p>

	</div>
	<%= f.submit  class: "btn btn-primary"%>

<% end %>
<%= link_to "Back to articles Listing", articles_path %>

</div>

app/views/articles/edit.html.erb
<h1> Edit existing article</h1>
       
<%= render 'form' %>

app/views/articles/index.html.erb
<div class="container text-center">
<h1>List of all articles</h1>


<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
  Click to Save
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Are you sure?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>


<p>
<%= link_to "Create new article", new_article_path %>
</p>
<table class="table table-hover">
	<thead class="thead-dark">
	<tr>
		<th>Title</th>
		<th>Description </th>
		<th></th>
		<th></th>
		<th></th>
       </tr>
       </thead>
	       <tbody>
	       <% @articles.each do |article| %>
		       <tr>
			       <td><%= article.title %></td>
			       <td><%= article.description %></td>
			       <td><%= link_to 'Edit', edit_article_path(article) %></td>
			       <td><%= link_to 'Show', article_path(article) %></td>
			       <td><%= link_to 'Delete', article_path(article), method: :delete, data: {confirm: "Are you sure?"}%></td>
		       </tr>
	       <%end%>
	       </tbody>

</table>
</div>

app/views/articles/new.html.erb
<h1>THIS IS A NEW ARTICLE</h1>
<%= render 'form' %>

app/views/articles/show.html.erb
<div class = "container text-center">
	
		<h1>Showing selected article</h1>

<p>
<div class = "card">
	<div class="card-header">This is the Article details</div>
	<div class="card-content">
		<Strong>	Title:</Strong> <%= @article.title %>

</p>

<p>

<Strong>Description: </Strong><%= @article.description %>

</p>
	</div>
	<div class="card-footer">


<h2>Comments</h2>
<%= render @article.comments %>



<h2>Add a comment:</h2>
<%= render 'comments/form' %>


<%= link_to "Edit this article", edit_article_path(@article) %> | 
<%= link_to "Back to articles Listing", articles_path %>
</div>

</div>

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>
 
<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<p>
  <%= link_to 'Destroy Comment', [comment.article, comment],
                 method: :delete,
		                data: { confirm: 'Are you sure?' } %>
			</p>

app/views/comments/_form.html.erb
<%= form_with(model: [ @article, @article.comments.build ], local: true) do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/layouts/_footer.erb
<!--<footer class="main-footer">
  <strong>Copyright © 2020 Signalwire Support by Fred.</strong>
  All rights reserved.
</footer> -->

<div class="footer text-right">
            <div>
               fred@signalwire.com  <strong>Copyright</strong> for signalwire staff &copy; 2020
            </div>
        </div>
	
	
	</div>
</div>

app/views/layouts/_header.erb
<div id="page-wrapper" class="gray-bg text-center">
        <div class="row border-bottom">
        <nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0">

            <ul class="nav navbar-top-links navbar-right">
                <li>
                    <span class="m-r-sm text-muted welcome-message">Welcome to SignalWire support Testing Tools.</span>
                </li>
              
                    


                <li>
                    <!--<a href="login.html"> -->
					<a href="#">
                        <i class="fa fa-sign-out"></i> Log out
                    </a>
                </li>
            </ul>

        </nav>
        </div>
<!-- Heading section ends here.-->

            <div class="row wrapper border-bottom white-bg page-heading">
                <div class="col-lg-10">
                    <h2><strong>SignalWire Support Tools</strong></h2>
                   <!-- <ol class="breadcrumb">
                        <li>
                            <a href="index.html">Home</a>
                        </li>
                        <li>
                            <a>Forms</a>
                        </li>
                        <li class="active">
                            <strong>signalwire test tools</strong>
                        </li>
                    </ol> -->
                </div>
                <div class="col-lg-2">

		</div>

		</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>

            <ul>

                    <li><%= msg %></li>

            </ul>

    <% end %>

app/views/layouts/_sidebar.erb
		<div class="sidebar">
  <a class="active" href="#home">Home</a>
  <a href="#news">News</a>
  <%= link_to "List all Articles", articles_path %> </a>
  <%= link_to "Create New Article", new_article_path %> 
  <a href="#contact">Contact</a>
  <a href="#about">About</a>





    </div>

app/views/layouts/_test.html.erb
<div class="container-fluid">

	<!-- GRID-->
<div class="container">
  <div class="row">
    <div class="col-sm">
      One of three columns
    </div>
    <div class="col-sm">
      One of three columns
    </div>
    <div class="col-sm">
      One of three columns
    </div>
  </div>
</div>

<!-- GRID ends>


<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>


<button type="button" class="btn btn-lg btn-danger" data-toggle="popover" title="Popover title" data-content="And here's some amazing content. It's very engaging. Right?">Click to toggle popover</button>




<button type="button" class="btn btn-secondary" data-container="body" data-toggle="popover" data-placement="top" data-content="Vivamus sagittis lacus vel augue laoreet rutrum faucibus.">
  Popover on top
</button>

<button type="button" class="btn btn-secondary" data-container="body" data-toggle="popover" data-placement="right" data-content="Vivamus sagittis lacus vel augue laoreet rutrum faucibus.">
  Popover on right
</button>

<button type="button" class="btn btn-secondary" data-container="body" data-toggle="popover" data-placement="bottom" data-content="Vivamus
sagittis lacus vel augue laoreet rutrum faucibus.">
  Popover on bottom
</button>

<button type="button" class="btn btn-secondary" data-container="body" data-toggle="popover" data-placement="left" data-content="Vivamus sagittis lacus vel augue laoreet rutrum faucibus.">
  Popover on left
</button>


<!-- Example single danger button -->
<div class="btn-group">
  <button type="button" class="btn btn-danger dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Action
  </button>
  <div class="dropdown-menu">
    <a class="dropdown-item" href="#">Action</a>
    <a class="dropdown-item" href="#">Another action</a>
    <a class="dropdown-item" href="#">Something else here</a>
    <div class="dropdown-divider"></div>
    <a class="dropdown-item" href="#">Separated link</a>
  </div>
</div>



<div class="modal-body">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-4">.col-md-4</div>
      <div class="col-md-4 ml-auto">.col-md-4 .ml-auto</div>
    </div>
    <div class="row">
      <div class="col-md-3 ml-auto">.col-md-3 .ml-auto</div>
      <div class="col-md-2 ml-auto">.col-md-2 .ml-auto</div>
    </div>
    <div class="row">
      <div class="col-md-6 ml-auto">.col-md-6 .ml-auto</div>
    </div>
    <div class="row">
      <div class="col-sm-9">
        Level 1: .col-sm-9
        <div class="row">
          <div class="col-8 col-sm-6">
            Level 2: .col-8 .col-sm-6
          </div>
          <div class="col-4 col-sm-6">
            Level 2: .col-4 .col-sm-6
          </div>
        </div>
      </div>
    </div>
  </div>
</div>












<table class="table table-striped table-dark">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">First</th>
      <th scope="col">Last</th>
      <th scope="col">Handle</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">1</th>
      <td>Mark</td>
      <td>Otto</td>
      <td>@mdo</td>
    </tr>
    <tr>
      <th scope="row">2</th>
      <td>Jacob</td>
      <td>Thornton</td>
      <td>@fat</td>
    </tr>
    <tr>
      <th scope="row">3</th>
      <td>Larry</td>
      <td>the Bird</td>
      <td>@twitter</td>
    </tr>
  </tbody>
</table>



<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
    <li class="page-item disabled">
      <a class="page-link" href="#" tabindex="-1">Previous</a>
    </li>
    <li class="page-item"><a class="page-link" href="#">1</a></li>
    <li class="page-item"><a class="page-link" href="#">2</a></li>
    <li class="page-item"><a class="page-link" href="#">3</a></li>
    <li class="page-item">
      <a class="page-link" href="#">Next</a>
    </li>
  </ul>
</nav>





</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/6d90f39943.js"></script>

  </head>

  <body >
	  
		  <%= render 'layouts/header' %>
		  <%= render 'layouts/messages' %> 
		  <%= render 'layouts/sidebar' %>
		  <div class="content">
			  <%= yield %>
		  </div>
		  
		  <%= render 'layouts/footer' %> 
	  
  </body>
</html>

app/views/layouts/saved_header.erb
<nav
  class="main-header navbar navbar-expand navbar-white navbar-light border-bottom"
>
  <!-- Left navbar links -->
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" data-widget="pushmenu" href="#"
        ><i class="fas fa-bars"></i
      ></a>
    </li>
    <li class="nav-item d-none d-sm-inline-block">
      <a href="index3.html" class="nav-link">Home</a>
    </li>
    <li class="nav-item d-none d-sm-inline-block">
      <a href="#" class="nav-link">Contact</a>
    </li>
  </ul>
  <!-- SEARCH FORM -->
  <form class="form-inline ml-3">
    <div class="input-group input-group-sm">
      <input
        class="form-control form-control-navbar"
        type="search"
        placeholder="Search"
        aria-label="Search"
      />
      <div class="input-group-append">
        <button class="btn btn-navbar" type="submit">
          <i class="fas fa-search"></i>
        </button>
      </div>
    </div>
  </form>
  <!-- Right navbar links -->
  <ul class="navbar-nav ml-auto">
    <!-- Messages Dropdown Menu -->
    <li class="nav-item dropdown">
      <a class="nav-link" data-toggle="dropdown" href="#">
        <i class="far fa-comments"></i>
        <span class="badge badge-danger navbar-badge">3</span>
      </a>
      <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
        <a href="#" class="dropdown-item">
          <!-- Message Start -->
          <div class="media">
            <img
              src="http://placehold.it/128x128"
              alt="User Avatar"
              class="img-size-50 mr-3 img-circle"
            />
            <div class="media-body">
              <h3 class="dropdown-item-title">
                Brad Diesel
                <span class="float-right text-sm text-danger"
                  ><i class="fas fa-star"></i
                ></span>
              </h3>
              <p class="text-sm">Call me whenever you can...</p>
              <p class="text-sm text-muted">
                <i class="far fa-clock mr-1"></i> 4 Hours Ago
              </p>
            </div>
          </div>
          <!-- Message End -->
        </a>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item">
          <!-- Message Start -->
          <div class="media">
            <img
              src="http://placehold.it/128x128"
              alt="User Avatar"
              class="img-size-50 img-circle mr-3"
            />
            <div class="media-body">
              <h3 class="dropdown-item-title">
                John Pierce
                <span class="float-right text-sm text-muted"
                  ><i class="fas fa-star"></i
                ></span>
              </h3>
              <p class="text-sm">I got your message bro</p>
              <p class="text-sm text-muted">
                <i class="far fa-clock mr-1"></i> 4 Hours Ago
              </p>
            </div>
          </div>
          <!-- Message End -->
        </a>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item">
          <!-- Message Start -->
          <div class="media">
            <img
              src="http://placehold.it/128x128"
              alt="User Avatar"
              class="img-size-50 img-circle mr-3"
            />
            <div class="media-body">
              <h3 class="dropdown-item-title">
                Nora Silvester
                <span class="float-right text-sm text-warning"
                  ><i class="fas fa-star"></i
                ></span>
              </h3>
              <p class="text-sm">The subject goes here</p>
              <p class="text-sm text-muted">
                <i class="far fa-clock mr-1"></i> 4 Hours Ago
              </p>
            </div>
          </div>
          <!-- Message End -->
        </a>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
      </div>
    </li>
    <!-- Notifications Dropdown Menu -->
    <li class="nav-item dropdown">
      <a class="nav-link" data-toggle="dropdown" href="#">
        <i class="far fa-bell"></i>
        <span class="badge badge-warning navbar-badge">15</span>
      </a>
      <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
        <span class="dropdown-item dropdown-header">15 Notifications</span>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item">
          <i class="fas fa-envelope mr-2"></i> 4 new messages
          <span class="float-right text-muted text-sm">3 mins</span>
        </a>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item">
          <i class="fas fa-users mr-2"></i> 8 friend requests
          <span class="float-right text-muted text-sm">12 hours</span>
        </a>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item">
          <i class="fas fa-file mr-2"></i> 3 new reports
          <span class="float-right text-muted text-sm">2 days</span>
        </a>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item dropdown-footer"
          >See All Notifications</a
        >
      </div>
    </li>
    <li class="nav-item">
      <a
        class="nav-link"
        data-widget="control-sidebar"
        data-slide="true"
        href="#"
        ><i class="fas fa-th-large"></i
      ></a>
    </li>
  </ul>
</nav>

app/views/welcome/about.html.erb
<h2>ABOUT US PAGE </h2>

<p />
<%= link_to 'HOME', welcome_home_path %>

app/views/welcome/home.html.erb
<h1> WELCOME HOME </h1>

<p/>
<%= link_to 'ABOUT US', welcome_about_path %>